/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TRUE = 5;
  /** RegularExpression Id. */
  int FALSE = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int VAR = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int NUM = 10;
  /** RegularExpression Id. */
  int PLUS = 11;
  /** RegularExpression Id. */
  int MINUS = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int LEFTP = 16;
  /** RegularExpression Id. */
  int RIGHTP = 17;
  /** RegularExpression Id. */
  int THEN = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int SKIPCOMMAND = 22;
  /** RegularExpression Id. */
  int ISEQUAL = 23;
  /** RegularExpression Id. */
  int EQUALS = 24;
  /** RegularExpression Id. */
  int SEMICOLON = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"tt\"",
    "\"ff\"",
    "<LETTER>",
    "<VAR>",
    "<DIGIT>",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"!\"",
    "\"^\"",
    "\"if\"",
    "\"(\"",
    "\")\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"skip\"",
    "\"==\"",
    "\":=\"",
    "\";\"",
  };

}
